### ISSUE TITLE
script rewriting throws UnicodeDecodeError when it encounters binary file

### ISSUE THREAD

**Issue by wojdyr** [scikit-build/scikit-build-core#293]
I'm installing binary program directly to bin (with this [CmakeLists.txt][1]).
After upgrading from 0.2.1 to 0.3.1 I got this error:

      [100%] Built target trigger
      -- Install configuration: "Release"
      -- Installing: /tmp/tmp284d30cb/wheel/scripts/gemmi
      *** scikit-build-core 0.3.1 using CMake 3.26.3
      *** Configurating CMake...
      *** Building project with Unknown...
      *** Installing project into wheel...
      *** Making wheel...
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-9_hn868s/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/__init__.py", line 32, in build_wheel
          return _build_wheel_impl(
        File "/tmp/pip-build-env-9_hn868s/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/wheel.py", line 211, in _build_wheel_impl
          process_script_dir(wheel_dirs["scripts"])
        File "/tmp/pip-build-env-9_hn868s/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/_scripts.py", line 23, in process_script_dir
          first_line = next(file_iter)
        File "/usr/lib/python3.10/codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 25: invalid continuation byte
      [end of output]

which I think is related to script rewriting in #254.

[1]: https://github.com/project-gemmi/gemmi_program_wheel/blob/main/CMakeLists.txt

**Comment by henryiii** [comment]
Yes, that needs to be protected. The first draft opened it in binary and I forgot that it would fail on binaries when I changed it to opening it with encoding.

This does mean we don’t support shabang rewriting on .pyz files. Not sure if anyone will be doing that, though, so protecting this is a good first step.
