### ISSUE TITLE
nox: session "tests" failed because of TypeError: _run_tests() missing 1 required keyword-only argument: 'install_args'

### ISSUE THREAD

**Issue by mgorny** [scikit-build/scikit-build-core#404]
```
$ nox -e tests
nox > Running session tests
nox > Creating virtual environment (virtualenv) using python3.12 in .nox/tests
nox > Session tests raised exception TypeError("_run_tests() missing 1 required keyword-only argument: 'install_args'")
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nox/sessions.py", line 761, in execute
    self.func(session)
  File "/usr/lib/python3.12/site-packages/nox/_decorators.py", line 75, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/scikit-build-core/noxfile.py", line 68, in tests
    _run_tests(session, extras=["test-meta,test-numpy"])
TypeError: _run_tests() missing 1 required keyword-only argument: 'install_args'
nox > Session tests failed.
```

**Comment by LecrisUT** [comment]
Nox or python 3.12 issue I wonder. The CI only tests with python 3.11

**Comment by henryiii** [comment]
I bet this is something I broke when I refactored this in nox in 0.4.6 to use the smaller individual extras.

We do test on 3.12, but we don't run all the nox sessions in CI, I mostly do that locally.

**Comment by mgorny** [comment]
Thanks!
