### ISSUE TITLE
scikit-build-core dynamic versioning problems with non-top level package structure

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-build/scikit-build-core#495]
## Reprodcution

This issue exists as a GitHub repository at https://github.com/matthewfeickert/scikit-build-core-example

## Summary of problem

I have a problem when packaging a `scikit-build-core` based project that uses version control for dynamic versioning (here using a similar example package as provided in the https://learn.scientific-python.org/development/guides/packaging-compiled/ examples)

The repository directory structure (intentionally using a subdirectory to provide an example) is

```console
$ tree .
.
├── README.md
└── subdir
    ├── CMakeLists.txt
    ├── pyproject.toml
    ├── README.md
    └── src
        ├── basic_math.cpp
        └── example_pkg
            └── __init__.py

3 directories, 6 files
```

If we navigate to the package directory

```
cd subdir
```

then with the current `pyproject.toml` structure to use version control for dynamic versioning (as suggested by `cookie`)

```toml
...

[tool.scikit-build]
minimum-version = "0.4"
build-dir = "build/{wheel_tag}"
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.include = ["src/example_pkg/_version.py"]

[tool.setuptools_scm]
local_scheme = "no-local-version"
# Need to give root as we aren't at the same level as the git repo
root = ".."
# Need to provide path relative to root
write_to = "subdir/src/example_pkg/_version.py"

...
```

### a local install works

```console
$ rm -rf src/example_pkg/_version.py && rm -rf build && python -m pip install --upgrade .
Processing /home/feickert/Code/debug/sckit-build-core-example/subdir
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/feickert/.pyenv/versions/talk-odsl-forum-seminar-2023/lib/python3.11/site-packages (from example-pkg==0.1.dev0) (1.25.2)
Building wheels for collected packages: example-pkg
  Building wheel for example-pkg (pyproject.toml) ... done
  Created wheel for example-pkg: filename=example_pkg-0.1.dev0-cp311-cp311-manylinux_2_35_x86_64.whl size=51989 sha256=d9fd4fe4e71e867f75eeb7aae6b9f1816c070e316fde599e79e756a2fac6d3fb
  Stored in directory: /tmp/pip-ephem-wheel-cache-pdx70379/wheels/68/52/95/2ed862a321a9b5f7a76e23e273f0b64a03d5771eae1e8a411f
Successfully built example-pkg
Installing collected packages: example-pkg
Successfully installed example-pkg-0.1.dev0
$ cat src/example_pkg/_version.py
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev0'
__version_tuple__ = version_tuple = (0, 1, 'dev0')
```

### but building a wheel fails

```console
$ rm -rf src/example_pkg/_version.py && rm -rf dist && python -m build .
* Creating venv isolated environment...
* Installing packages in isolated environment... (pybind11, scikit-build-core)
* Getting build dependencies for sdist...
* Installing packages in isolated environment... (pathspec, pyproject_metadata, setuptools-scm)
* Building sdist...
*** scikit-build-core 0.5.0 (sdist)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (pybind11, scikit-build-core)
* Getting build dependencies for wheel...
* Installing packages in isolated environment... (pathspec, pyproject_metadata, setuptools-scm)
* Building wheel...
Traceback (most recent call last):
  File "/home/feickert/.pyenv/versions/talk-odsl-forum-seminar-2023/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/feickert/.pyenv/versions/talk-odsl-forum-seminar-2023/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feickert/.pyenv/versions/talk-odsl-forum-seminar-2023/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-w_pvzrk7/lib/python3.11/site-packages/scikit_build_core/build/__init__.py", line 32, in build_wheel
    return _build_wheel_impl(
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-w_pvzrk7/lib/python3.11/site-packages/scikit_build_core/build/wheel.py", line 92, in _build_wheel_impl
    metadata = get_standard_metadata(pyproject, settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-w_pvzrk7/lib/python3.11/site-packages/scikit_build_core/settings/metadata.py", line 33, in get_standard_metadata
    new_pyproject_dict["project"][field] = provider.dynamic_metadata(field, config)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-w_pvzrk7/lib/python3.11/site-packages/scikit_build_core/metadata/setuptools_scm.py", line 28, in dynamic_metadata
    version: str = _get_version(config)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-w_pvzrk7/lib/python3.11/site-packages/setuptools_scm/__init__.py", line 162, in _get_version
    dump_version(
  File "/tmp/build-env-w_pvzrk7/lib/python3.11/site-packages/setuptools_scm/__init__.py", line 77, in dump_version
    with open(target, "w") as fp:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../subdir/src/example_pkg/_version.py'

ERROR Backend subprocess exited when trying to invoke build_wheel
```

How should the relative directory information be provided such that both a local install and an isolated build work correctly?
I understand that the sdist has a different directory structure than the repository

```console
$ tar -xzvf dist/example-pkg*.tar.gz
$ tree example-pkg-*/
example-pkg-0.1.dev9/
├── CMakeLists.txt
├── PKG-INFO
├── pyproject.toml
├── README.md
└── src
    ├── basic_math.cpp
    └── example_pkg
        ├── __init__.py
        └── _version.py

2 directories, 7 files
```

and so now the `setuptools_scm` relative path information is wrong

```console
$ grep root example-pkg-0.1.dev9/pyproject.toml
# Need to give root as we aren't at the same level as the git repo
root = ".."
# Need to provide path relative to root
```

but I don't know how to correct for this.

## Aside

`setuptool_scm` currently recommends using `relative_to` and `version_file` instead of `root` and `write_to` as these later options are now [viewed as deprecated](https://github.com/pypa/setuptools_scm/blob/5b1c77b71ebf66413f3ecfea2222b5b3e0a26bcd/docs/config.md?plain=1#L36), however trying to use `relative_to` and `version_file` fails with `scikit-build-core` as `version_file` is not recognized.

**Comment by henryiii** [comment]
Those features are from the new, unreleased version (which will break scikit-build-core, I believe, since `_get_version` is being dropped, and `get_version` is deprecated and can't read `tool.setuptools_scm`. Let's see what happens there first. I'll also see if I can move along the `dynamic-metadata` plugin project; the ideal long-term solution would be for `setuptools_scm` to natively support being used as a plugin following `dynamic-metadata`'s spec. CC @RonnyPfannschmidt.

Main holdup for dynamic-metadata is making sure we have a good spec.

**Comment by RonnyPfannschmidt** [comment]
planned 8.x release before this weekend

**Comment by henryiii** [comment]
@matthewfeickert what happens if you use https://scikit-build-core.readthedocs.io/en/latest/configuration.html#writing-metadata instead of writing natively with `setuptools_scm`?

**Comment by matthewfeickert** [comment]
@henryiii Unless I'm configuring things wrong, this seems to only support static metadata at the moment

```diff
-[tool.scikit-build]
-minimum-version = "0.4"
-build-dir = "build/{wheel_tag}"
-metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
-sdist.include = ["src/example_pkg/_version.py"]
-
-[tool.setuptools_scm]
-local_scheme = "no-local-version"
-# Need to give root as we aren't at the same level as the git repo
-root = ".."
-# Need to provide path relative to root
-write_to = "subdir/src/example_pkg/_version.py"
+[[tool.scikit-build.generate]]
+path = "src/example_pkg/_version.py"
+template = '''
+version = "${version}"
+'''
```

```console
$ rm -rf src/example_pkg/_version.py && rm -rf build && python -m pip install --upgrade .
Processing /home/feickert/Code/debug/scikit-build-core-example/subdir
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/feickert/.pyenv/versions/scikit-build-core-example/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/feickert/.pyenv/versions/scikit-build-core-example/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/feickert/.pyenv/versions/scikit-build-core-example/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-smfoshhh/overlay/lib/python3.11/site-packages/scikit_build_core/build/__init__.py", line 73, in prepare_metadata_for_build_wheel
          return _build_wheel_impl(
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-smfoshhh/overlay/lib/python3.11/site-packages/scikit_build_core/build/wheel.py", line 96, in _build_wheel_impl
          raise AssertionError(msg)
      AssertionError: project.version is not statically specified, must be present currently
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

```console
$ rm -rf src/example_pkg/_version.py && rm -rf dist && python -m build . 
* Creating venv isolated environment...
* Installing packages in isolated environment... (pybind11, scikit-build-core)
* Getting build dependencies for sdist...
* Installing packages in isolated environment... (pathspec, pyproject_metadata)
* Building sdist...
*** scikit-build-core 0.5.0 (sdist)
Traceback (most recent call last):
  File "/home/feickert/.pyenv/versions/scikit-build-core-example/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/feickert/.pyenv/versions/scikit-build-core-example/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feickert/.pyenv/versions/scikit-build-core-example/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 304, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-j8la7upi/lib/python3.11/site-packages/scikit_build_core/build/__init__.py", line 97, in build_sdist
    return skbuild_build_sdist(sdist_directory, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-j8la7upi/lib/python3.11/site-packages/scikit_build_core/build/sdist.py", line 116, in build_sdist
    pkg_info = bytes(copy.deepcopy(metadata).as_rfc822())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-j8la7upi/lib/python3.11/site-packages/pyproject_metadata/__init__.py", line 263, in as_rfc822
    self.write_to_rfc822(message)
  File "/tmp/build-env-j8la7upi/lib/python3.11/site-packages/pyproject_metadata/__init__.py", line 270, in write_to_rfc822
    raise ConfigurationError('Missing version field')
pyproject_metadata.ConfigurationError: Missing version field

ERROR Backend subprocess exited when trying to invoke build_sdist
```

**Comment by henryiii** [comment]
You still need the 
```toml
[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
```
part.

**Comment by matthewfeickert** [comment]
I'm about to go AFK so I'll have to give more clear feedback later, but

```diff
 [tool.scikit-build]
-minimum-version = "0.4"
-build-dir = "build/{wheel_tag}"
 metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
-sdist.include = ["src/example_pkg/_version.py"]
 
-[tool.setuptools_scm]
-local_scheme = "no-local-version"
-# Need to give root as we aren't at the same level as the git repo
-root = ".."
-# Need to provide path relative to root
-write_to = "subdir/src/example_pkg/_version.py"
+[[tool.scikit-build.generate]]
+path = "example_pkg/_version.py"
+template = '''
+version = "${version}"
+'''
```

then raises

```
LookupError: pyproject.toml does not contain a tool.setuptools_scm section
```

**Comment by matthewfeickert** [comment]
The fix (seen in https://github.com/matthewfeickert/scikit-build-core-example/pull/2 provided by @henryiii and @LecrisUT) was to use `tool.scikit-build.generate` to write out the version information file along with using `setuptools_scm`'s `root` option to define the path to the top level of the Git repository.

```toml
...
[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"

[tool.setuptools_scm]
# Need to give root as we aren't at the same level as the git repo
root = ".."

[[tool.scikit-build.generate]]
path = "example_pkg/_version.py"
template = '''
version = "${version}"
'''
```

The full working `pyproject.toml` used is as follows:

```toml
[build-system]
requires = [
  "scikit-build-core>=0.5.0",
  "pybind11>=2.10.0"
  ]
build-backend = "scikit_build_core.build"


[project]
name = "example-pkg"
dynamic = ["version"]
description = "Example package for demonstration"
readme = "README.md"
authors = [
  { name = "Matthew Feickert", email = "matthew.feickert@cern.ch" },
]
maintainers = [
  { name = "Matthew Feickert", email = "matthew.feickert@cern.ch" },
]
requires-python = ">=3.8"

dependencies = [
    "numpy",
]

[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"

[tool.setuptools_scm]
# Ignore the commit hash in version
local_scheme = "no-local-version"
# Need to give root as we aren't at the same level as the git repo
root = ".."

[[tool.scikit-build.generate]]
path = "example_pkg/_version.py"
template = '''
version = "${version}"
'''
```
