### ISSUE TITLE
 scikit_build_core.errors.CMakeNotFoundError: Could not find CMake with version >= 3.12

### ISSUE THREAD

**Issue by DaveScream** [scikit-build/scikit-build-core#500]
`C:\Users\F2>cmake --version
cmake version 3.26.4-msvc4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

C:\Users\F2>where cmake
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe

C:\Users\F2>python -m pip install llama-cpp-python --force-reinstall --upgrade --no-build-isolation -v
Using pip 23.0.1 from C:\Python310\lib\site-packages\pip (python 3.10)
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.2.6.tar.gz (1.6 MB)
  Running command Preparing metadata (pyproject.toml)
  2023-09-17 22:51:22,033 - scikit_build_core - WARNING - Could not determine CMake version, got 'cmake version 3.26.4-msvc4\n\nCMake suite maintained and supported by Kitware (kitware.com/cmake).\n'
  Traceback (most recent call last):
    File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Python310\lib\site-packages\scikit_build_core\build\__init__.py", line 73, in prepare_metadata_for_build_wheel
      return _build_wheel_impl(
    File "C:\Python310\lib\site-packages\scikit_build_core\build\wheel.py", line 106, in _build_wheel_impl
      cmake = CMake.default_search(minimum_version=settings.cmake.minimum_version)
    File "C:\Python310\lib\site-packages\scikit_build_core\cmake.py", line 49, in default_search
      raise CMakeNotFoundError(msg)
  scikit_build_core.errors.CMakeNotFoundError: Could not find CMake with version >= 3.12
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Python310\python.exe' 'C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Temp\tmpxp4x5hqz'
  cwd: C:\temp\pip-install-e3s9k50w\llama-cpp-python_170c3a56e66a46bbb21c22d5e92eeaf7
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\F2>
`

**Comment by DaveScream** [comment]
Problem solved. I should use official cmake distribution, not packed with microsoft visual studio 2022 or  build tools 2022.

**Comment by henryiii** [comment]
We should allow parsing 3.26.4-msvc4. It should work fine as 3.26.4. Should be easy to include.
