### ISSUE TITLE
error message should be more apparent when setuptools_scm is used and no git version found

### ISSUE THREAD

**Issue by njzjz** [scikit-build/scikit-build-core#520]
I got the following error message when I used the `setuptools_scm` plugin and forgot to install `git` in a docker container.

```
  Traceback (most recent call last):
    File "/__w/_tool/Python/3.11.5/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/__w/_tool/Python/3.11.5/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/__w/_tool/Python/3.11.5/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
      return hook(metadata_directory, config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-afsbzgwk/overlay/lib/python3.11/site-packages/scikit_build_core/build/__init__.py", line 86, in prepare_metadata_for_build_editable
      return _build_wheel_impl(
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-afsbzgwk/overlay/lib/python3.11/site-packages/scikit_build_core/build/wheel.py", line 95, in _build_wheel_impl
      metadata = get_standard_metadata(pyproject, settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-afsbzgwk/overlay/lib/python3.11/site-packages/scikit_build_core/settings/metadata.py", line 39, in get_standard_metadata
      metadata = StandardMetadata.from_pyproject(new_pyproject_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-afsbzgwk/normal/lib/python3.11/site-packages/pyproject_metadata/__init__.py", line 226, in from_pyproject
      version_string = fetcher.get_str('project.version')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-afsbzgwk/normal/lib/python3.11/site-packages/pyproject_metadata/__init__.py", line 91, in get_str
      raise ConfigurationError(
  pyproject_metadata.ConfigurationError: Field `project.version` has an invalid type, expecting a string (got `None`)
  error: subprocess-exited-with-error
```

I realize that the reason is `git` is not installed in the container, and `actions/checkout` fetches a tarball instead of a git repository for me, so `setuptools-scm` returns `None` as the version. However, the error message should be more apparent when the version is `None`. The user (who is not a developer) may be confused about such an error message.

`setuptools-scm` already has an error message: https://github.com/pypa/setuptools_scm/blob/b877fb8740d752195c54da8167a35dfd0c68558f/src/setuptools_scm/_get_version_impl.py#L111-L121 and scikit-build-core never calls this method.

**Comment by LecrisUT** [comment]
There can be many sources of error as to why `setuptools-scm` gives none, and often times is configuration error of the project, e.g. wrong path to git root, missing `git_archival.txt` etc. I don't think it will be feasible for skbuild-core to determine the source of those error.

But what can be done is to check that the scm version is not None, otherwise throw an error that `setuptools-scm` might be misconfigured. Question though, are there reasonable usecases where those checks might impend other's workflow, e.g. manually setting fallback version?
