### ISSUE TITLE
ModuleNotFoundError: No module named 'pathspec'

### ISSUE THREAD

**Issue by mgehre-amd** [scikit-build/scikit-build-core#650]
Hi, and thanks for this amazing project!

`pip install --no-build-isolation -e`
causes
```
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/frob/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/frob/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/frob/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/frob/lib/python3.10/site-packages/scikit_build_core/build/__init__.py", line 83, in prepare_metadata_for_build_editable
          from .wheel import _build_wheel_impl
        File "/frob/lib/python3.10/site-packages/scikit_build_core/build/wheel.py", line 22, in <module>
          from ._editable import editable_redirect, libdir_to_installed, mapping_to_modules
        File "/frob/lib/python3.10/site-packages/scikit_build_core/build/_editable.py", line 8, in <module>
          from ._pathutil import (
        File "/frob/lib/python3.10/site-packages/scikit_build_core/build/_pathutil.py", line 7, in <module>
          from ._file_processor import each_unignored_file
        File "/frob/lib/python3.10/site-packages/scikit_build_core/build/_file_processor.py", line 8, in <module>
          import pathspec
      ModuleNotFoundError: No module named 'pathspec'
```
If scikit-build-core needs `pathspec`, shouldn't the `scikit-build-core` wheel depend on it? The same also applies to `pyproject_metadata`.

**Comment by henryiii** [comment]
Dup of https://github.com/scikit-build/scikit-build-core/issues/280. The problem is that this is not _just_ a pyproject builder, but also a tool for building plugins, including setuptools and a WIP hatchling plugin. These plugins don't need pathspec or pyproject_metadata, those are useless[^1] in plugin mode. You can install this with those requirements using `pip install scikit-build-core[pyproject]`, which will include everything you need for the pyproject-based builder.

If Python supported opt-out dependencies (like Rust), then these would 100% be opt-out instead of opt-in. But it doesn't.

Also, I think these are very light weight, so as some point we might just go ahead and require them. Let's see how the hatchling plugin goes before deciding, though.

[^1]: If it turns those those do need one of these, like pathspec, then I think we should just go ahead and including them.

**Comment by mgehre-amd** [comment]
Thanks for clarifying. Will close this as dup of #280. I'd really like to see the getting started documentation to mention `scikit-build-core[pyproject]` in the pyproject.toml examples.
