### ISSUE TITLE
Building failed on system of non utf-8 default charset with `.gitignore` containing non-ascii characters

### ISSUE THREAD

**Issue by Starry-OvO** [scikit-build/scikit-build-core#859]
For some computer system with default charset of non utf-8, e.g. Microsoft Windows in China (GBK), Japan (SJIS) and South Korea (EUC-KR), the `p.read_text()` always tries to use the system default charset to decode the `.gitignore` encoded in `utf-8` (sometimes these `.gitignore`s are auto-generated by IDE like PyCharm). When any `.gitignore` contains any non-ascii characters, the coding mismatch leads to an `UnicodeDecodeError` during the packing procedure.

https://github.com/scikit-build/scikit-build-core/blob/4f06e8cf8acc41c38c52152b6b8b2e0cbb321c34/src/scikit_build_core/build/_file_processor.py#L47

Since almost all `.gitignore`s are encoded in `utf-8`, maybe it is a better approach to pass the argument `encoding='utf-8'` to the `read_text`?

You can see the demo [here](https://github.com/Starry-OvO/scikit-build-core-issue-demo).

**Thanks for your great contribution, scikit-build helps me a lot in building hybrid-language projects!**

The full error log is:

```
$ rye build
Python version: cpython@3.12.4
building scikit-build-core-issue-demo
* Creating isolated environment: venv+uv...
* Using external uv from C:\Users\Administrator\.rye\uv\0.2.33\uv.EXE
* Installing packages in isolated environment:
  - scikit-build-core==0.10.2
* Getting build dependencies for sdist...
* Building sdist...
*** scikit-build-core 0.10.2 (sdist)
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\.tmpBv8U6T\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
    main()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\.tmpBv8U6T\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\Temp\.tmpBv8U6T\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 304, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-8bmczgpf\Lib\site-packages\scikit_build_core\build\__init__.py", line 103, in build_sdist
    return skbuild_build_sdist(sdist_directory, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-8bmczgpf\Lib\site-packages\scikit_build_core\build\sdist.py", line 152, in build_sdist
    paths = sorted(
            ^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-8bmczgpf\Lib\site-packages\scikit_build_core\build\_file_processor.py", line 47, in each_unignored_file
    p.parent: pathspec.GitIgnoreSpec.from_lines(p.read_text().splitlines())
                                                ^^^^^^^^^^^^^
  File "C:\Users\Administrator\.rye\py\cpython@3.12.4\Lib\pathlib.py", line 1028, in read_text
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 6: illegal multibyte sequence

ERROR Backend subprocess exited when trying to invoke build_sdist
error: failed to build dist
```

**Comment by henryiii** [comment]
I think this was an oversight, we should use `encoding="utf-8-sig"` everywhere.
