### ISSUE TITLE
 AttributeError: module 'pathspec' has no attribute 'GitIgnoreSpec'

### ISSUE THREAD

**Issue by Haoran-Zhao** [scikit-build/scikit-build-core#911]
I'm trying to build a wheel file using .tomol following the document

In the .toml
```
[build-system]
requires = [
    "scikit-build-core>=0.10.7",
    "nanobind>=1.5.2",
    "pathspec>=0.10.1"
]
build-backend = "scikit_build_core.build"
```
And it have been successfully installed as following:
```
 Running command pip subprocess to install build dependencies
  Collecting scikit-build-core>=0.10.7
    Using cached scikit_build_core-0.10.7-py3-none-any.whl (165 kB)
  Collecting nanobind>=1.5.2
    Downloading nanobind-2.1.0-py3-none-any.whl (220 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.7/220.7 KB 2.2 MB/s eta 0:00:00
  Collecting pathspec>=0.10.1
    Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
  Collecting tomli>=1.2.2
    Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting exceptiongroup>=1.0
    Using cached exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
  Collecting packaging>=21.3
    Downloading packaging-24.1-py3-none-any.whl (53 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 KB 13.2 MB/s eta 0:00:00
  Installing collected packages: nanobind, tomli, pathspec, packaging, exceptiongroup, scikit-build-core
  Successfully installed exceptiongroup-1.2.2 nanobind-2.1.0 packaging-24.1 pathspec-0.12.1 scikit-build-core-0.10.7 tomli-2.0.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command pip subprocess to install backend dependencies
  Collecting ninja>=1.5
    Downloading ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.2/307.2 KB 3.1 MB/s eta 0:00:00
  Installing collected packages: ninja
  Successfully installed ninja-1.11.1.1
  Installing backend dependencies ... done
  Running command Preparing metadata (pyproject.toml)
  *** scikit-build-core 0.10.7 using CMake 3.22.1 (metadata_wheel)
  2024-09-24 20:45:33,385 - scikit_build_core - WARNING - No license files found, set wheel.license-files to [] to suppress this warning
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: trajectory-optimization
  Running command Building wheel for trajectory-optimization (pyproject.toml)
  *** scikit-build-core 0.10.7 using CMake 3.22.1 (wheel)
  2024-09-24 20:45:33,508 - scikit_build_core - WARNING - No license files found, set wheel.license-files to [] to suppress this warning
  *** Configuring CMake...
```
The error msg is following
```
*** Making wheel...
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-z07wj52t/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/__init__.py", line 33, in build_wheel
      return _build_wheel_impl(
    File "/tmp/pip-build-env-z07wj52t/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/wheel.py", line 175, in _build_wheel_impl
      return _build_wheel_impl_impl(
    File "/tmp/pip-build-env-z07wj52t/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/wheel.py", line 445, in _build_wheel_impl_impl
      mapping = packages_to_file_mapping(
    File "/tmp/pip-build-env-z07wj52t/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/_pathutil.py", line 49, in packages_to_file_mapping
      exclude_spec = pathspec.GitIgnoreSpec.from_lines(target_exclude)
  AttributeError: module 'pathspec' has no attribute 'GitIgnoreSpec'
  error: subprocess-exited-with-error
  
  × Building wheel for trajectory-optimization (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```
I have check the pathspec-0.12.1 has the attribute. Did I missed any dependencies or set something wrong? thanks for your help in advance.

**Comment by henryiii** [comment]
Did you discover what was wrong? I’ve seen something like this once before with hatchling instead

**Comment by Haoran-Zhao** [comment]
@henryiii I found do this `sudo apt remove python3-pathspec` resolved the problem

**Comment by Haoran-Zhao** [comment]
@henryiii By the way I do have another usage question. I define a path in CmakeList and used in my c++ code. I set `wheel.cmake = true`, and during the building process, the path is assigned to `/tmp/tmpvg12j55o/wheel/platlib/share/....`. This path is no longer valid after. Is there way to work around this? thanks!

**Comment by henryiii** [comment]
You can set the `build-dir`, like:

```toml
[tool.scikit-build]
build-dir = "build/{wheel_tag}"
```

https://scikit-build-core.readthedocs.io/en/latest/configuration.html#other-options

**Comment by LecrisUT** [comment]
> @henryiii I found do this `sudo apt remove python3-pathspec` resolved the problem

That sound very weird, because the logs shows that it is running in build isolation. I suspect it is a similar case to https://github.com/pypa/pip/issues/12976, in which case you should see different outcomes if you run `uv pip install` or `python3 -m build`.

It does seem to be a continuous traceback from `/usr/lib/python3` to the `/tmp/pip-build-env-z07wj52t` paths.

**Comment by henryiii** [comment]
What path are you seeing in `/tmp`? If it's the pip-installed packages (like cmake, scikit-build-core, or any others you specify in `build-system.requires` will be installed by pip in a tmp location. The only way to avoid that is to build with `--no-build-isolation` and pre-install anything you need.

Though the binary and source dirs should not be in tmp.

**Comment by Haoran-Zhao** [comment]
@LecrisUT I found that solution from this [post](https://github.com/abetlen/llama-cpp-python/issues/707) , hope it can provide you more info

**Comment by Haoran-Zhao** [comment]
> What path are you seeing in `/tmp`? If it's the pip-installed packages (like cmake, scikit-build-core, or any others you specify in `build-system.requires` will be installed by pip in a tmp location. The only way to avoid that is to build with `--no-build-isolation` and pre-install anything you need.
> 
> Though the binary and source dirs should not be in tmp.

all my files are installed in `/tmp` as here
```
*** Installing project into wheel...
  -- Install configuration: "Release"
  -- Installing: /tmp/tmpdujd5gb3/wheel/platlib/include
  -- Installing: /tmp/tmpdujd5gb3/wheel/platlib/include/my_package
  -- Installing: /tmp/tmpdujd5gb3/wheel/platlib/include/my_package/utils
  -- Installing: /tmp/tmpdujd5gb3/wheel/platlib/include/my_package/utils/trajectory_utils.hpp
  -- Installing: /tmp/tmpdujd5gb3/wheel/platlib/share/my_package/urdf/panda.urdf
  ......
 -- Installing: /tmp/tmpdujd5gb3/wheel/platlib/lib/python3.10/site-packages/my_package/my_package_py.cpython-310-x86_64-linux-gnu.so
  -- Set runtime path of "/tmp/tmpdujd5gb3/wheel/platlib/lib/python3.10/site-packages/my_package/my_package_py.cpython-310-x86_64-linux-gnu.so" to ""
 .......
 -- Up-to-date: /tmp/tmpdujd5gb3/wheel/platlib/share/my_package/urdf/panda.urdf
```

**Comment by Haoran-Zhao** [comment]
right, but when I try to run my code after `pip install <wheel>`
it shows this
```
Error:   File /tmp/tmpdujd5gb3/wheel/platlib/share/my_package/urdf/panda.urdf does not exist
         at line 55 in ./urdf_parser/src/model.cpp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The file /tmp/tmpdujd5gb3/wheel/platlib/share/my_package/urdf/panda.urdf does not contain a valid URDF model.
```
I think the path is still use the `/tmp` due to the compiling process.

**Comment by LecrisUT** [comment]
That's a separate issue, it seems your package is not relocatable, i.e. if you copy the whole `CMAKE_INSTALL_PREFIX` to a different folder the project should still work (`LD_LIBRARY_PATH`/`RPATH` stuff excluded)

**Comment by Haoran-Zhao** [comment]
@henryiii @LecrisUT thanks so much for your guidance! I will open a new issue if it still a problem. I will try your suggestion first.
